"""add price, remove created_at

Revision ID: 983952b030d1
Revises: a4e715ed1e4d
Create Date: 2025-06-27 15:50:54.936683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983952b030d1'
down_revision: Union[str, Sequence[str], None] = 'a4e715ed1e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
