# Generated by Django 5.2.1 on 2025-05-25 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание категории (необязательно)', null=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите родительскую категорию для создания подкategории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accortement.category', verbose_name='Родительская категория')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('shipping', 'Доставляется'), ('delivered', 'Доставлено'), ('cancelled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара (обязательное поле)', max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Подробное описание товара', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара в рублях', max_digits=10, verbose_name='Цена')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Доступное количество товара на складе', verbose_name='Количество на складе')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления товара', verbose_name='Дата добавления')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accortement.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'shop_products',
                'ordering': ['-date_added'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accortement.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accortement.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accortement.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
