# Generated by Django 5.2.1 on 2025-05-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_book_genere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
    ]
